### ISSUE TITLE
Establish a roadmap

### ISSUE THREAD

**Issue by ZenTauro** [scuttlebutt-rust/documentation#1]
Divide the Secure Scuttlebutt specification into several parts and study how to implement them.

Resources about the protocol:
- [The Guide](https://ssbc.github.io/scuttlebutt-protocol-guide/)
- [The Handbook](https://handbook.scuttlebutt.nz/)
- [The Spec](https://spec.scuttlebutt.nz/)
- [Scuttlebot docs](https://ssbc.github.io/docs/)
- [Repo with links](https://github.com/ssbc/scuttlebutt-guide)
- [Scalable Secure Scuttlebutt](https://github.com/dominictarr/scalable-secure-scuttlebutt)

Edits: Add links

**Comment by ZenTauro** [comment]
We should probably use libsodium as explained [here](https://dominictarr.com/post/133109715357/which-js-crypto-library-should-i-use) (from the scuttlebutt's handbook)

**Comment by ZenTauro** [comment]
For the handshake, box stream and RPC we should take a look at P/Invoke to call native procedures.

Here are some links:
 - Xamarin Android: [Using native libraries](https://docs.microsoft.com/en-us/xamarin/android/platform/native-libraries)
 - Xamarin iOS: [forum post with working example](https://forums.xamarin.com/discussion/49944/worked-example-of-calling-unmanaged-c-from-c-using-pinvoke)

**Comment by ZenTauro** [comment]
The roadmap:
1. [x] ~~Implement a wrapper for the **shs handshake** around [the c version](https://github.com/sunrise-choir/shs1-c) based on the exposed API of the [rust version](https://github.com/sunrise-choir/ssb-handshake). [Docs](https://docs.rs/ssb-handshake/0.5.0/ssb_handshake/fn.client.html) of the exposed API.~~ Implementation from scratch in [scuttlebutt_crypto](https://github.com/radio-patio/scuttlebutt_crypto). 
2. [ ] Implement a wrapper for the **box stream** around [the c version]() based on the exposed API of the [rust version](https://github.com/sunrise-choir/ssb-boxstream). [Docs](https://docs.rs/ssb-boxstream/0.2.1/ssb_boxstream/) of the exposed API.
3. [ ] Design interface to interact with peers through a connection manager.
4. [ ] Create a class that encapsulates a connection with a peer.
5. [ ] Create a class that provides a service to retrieve a reference to a peer on which RPCs can be invoked.
